export const artworksData = [
  {
    id: "1",
    title: "Azure Dreams",
    year: 2024,
    medium: "Oil on Canvas",
    dimensions: '36" × 48"',
    description: "An exploration of emotion through bold brushstrokes and vibrant color interplay. This piece captures the tension between chaos and harmony.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/v1763031149/IMG_0061_alrqy1.webp",
    category: "Abstract",
    price: "$3,200",
    sold: "false",
  },
  {
    id: "2",
    title: "Mountain Reverie",
    year: 2023,
    medium: "Watercolor",
    dimensions: '24" × 18"',
    description: "Inspired by early morning hikes in the Cascades, this watercolor celebrates the ethereal beauty of dawn breaking over misty peaks.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/a_-90/v1763031082/IMG_0086_h8xzwm.webp",
    category: "Landscape",
    price: "$1,800",
    sold: "false",
  },
  {
    id: "3",
    title: "Silent Contemplation",
    year: 2024,
    medium: "Acrylic on Canvas",
    dimensions: '30" × 40"',
    description: "A study in minimalism and form. The stark monochrome palette invites viewers to find beauty in simplicity.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/a_-90/v1763031142/IMG_0064_ylapdf.webp",
    category: "Portrait",
    price: "$2,400",
    sold: "true",
  },
  {
    id: "4",
    title: "Tropical Abundance",
    year: 2023,
    medium: "Oil on Canvas",
    dimensions: '28" × 36"',
    description: "Lush botanical forms rendered with meticulous detail. This work celebrates the vitality and diversity of tropical ecosystems.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/v1763031139/IMG_0079_dtgcp5.webp",
    category: "Botanical",
    price: "$2,600",
    sold: "false",
  },
  {
    id: "5",
    title: "Storm's Embrace",
    year: 2022,
    medium: "Oil on Canvas",
    dimensions: '40" × 30"',
    description: "The raw power of nature captured in dramatic brushwork. Waves crash against an unseen shore under turbulent skies.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/a_-90/v1763031083/IMG_0080_okx9gt.webp",
    category: "Landscape",
    price: "$3,500",
    sold: "false",
  },
  {
    id: "6",
    title: "Earth Fragments",
    year: 2024,
    medium: "Mixed Media",
    dimensions: '24" × 24"',
    description: "Geometric abstraction inspired by natural forms and archaeological remnants. A meditation on time and texture.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/v1763031140/IMG_0077_qnng59.webp",
    category: "Abstract",
    price: "$2,100",
    sold: "false",
  },
  {
    id: "7",
    title: "Urban Twilight",
    year: 2023,
    medium: "Oil on Canvas",
    dimensions: '48" × 24"',
    description: "The city transforms as day becomes night. Impressionistic brushwork captures the fleeting magic of the golden hour.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/a_-90/v1763031082/IMG_0083_d8ng42.webp",
    category: "Cityscape",
    price: "$2,900",
    sold: "false",
  },
  {
    id: "8",
    title: "Peony Dreams",
    year: 2024,
    medium: "Oil on Canvas",
    dimensions: '20" × 30"',
    description: "Delicate florals rendered in soft, romantic tones. A celebration of natural beauty and the passage of seasons.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/v1763031080/IMG_0091_ovhfjz.webp",
    category: "Still Life",
    price: "$1,900",
    sold: "false",
  },
  {
    id: "9",
    title: "Golden Gesture",
    year: 2023,
    medium: "Ink and Gold Leaf on Paper",
    dimensions: '32" × 24"',
    description: "Bold, calligraphic marks dance across the surface. The interplay of black ink and precious metal creates visual drama.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/a_90/v1763031079/IMG_0094_qul10a.webp",
    category: "Abstract",
    price: "$2,800",
    sold: "true",
  },
  {
    id: "10",
    title: "Forest Light",
    year: 2024,
    medium: "Oil on Canvas",
    dimensions: '36" × 48"',
    description: "Sunlight filters through ancient trees, creating patterns of light and shadow. An immersive experience of nature's cathedral.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/v1763031141/IMG_0072_zdzfhs.webp",
    category: "Landscape",
    price: "$3,400",
    sold: "false",
  },
  {
    id: "11",
    title: "Movement in Red",
    year: 2023,
    medium: "Acrylic on Canvas",
    dimensions: '40" × 30"',
    description: "Capturing the ephemeral grace of dance through expressive brushwork and dynamic composition.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/a_-90/v1763031042/IMG_0098_ymjmvm.webp",
    category: "Figurative",
    price: "$3,100",
    sold: "false",
  },
  {
    id: "12",
    title: "Horizon Lines",
    year: 2024,
    medium: "Acrylic on Canvas",
    dimensions: '30" × 40"',
    description: "Minimalist color field painting exploring the subtle relationships between hue, value, and texture.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/v1763031040/IMG_0109_q7s0wl.webp",
    category: "Abstract",
    price: "$2,500",
    sold: "false",
  },
  {
    id: "13",
    title: "Architectural Memory",
    year: 2022,
    medium: "Oil on Canvas",
    dimensions: '36" × 48"',
    description: "Classical architecture rendered with precision and reverence. Light and shadow reveal the enduring beauty of form.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/a_-90/v1763031040/IMG_0104_os12jy.webp",
    category: "Architecture",
    price: "$3,300",
    sold: "false",
  },
  {
    id: "14",
    title: "Coastal Reverie",
    year: 2024,
    medium: "Oil on Canvas",
    dimensions: '48" × 20"',
    description: "Dramatic cliffs meet the endless ocean under a painted sky. A romantic vision of nature's grandeur.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/a_-90/v1763031038/IMG_0100_aiepe3.webp",
    category: "Landscape",
    price: "$3,600",
    sold: "false",
  },
  {
    id: "15",
    title: "Midnight Copper",
    year: 2023,
    medium: "Mixed Media with Metallic Accents",
    dimensions: '30" × 30"',
    description: "Layered textures and metallic elements create depth and luminosity. An exploration of material and surface.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/v1763031038/IMG_0113_lrpa37.webp",
    category: "Abstract",
    price: "$2,700",
    sold: "false",
  },
  {
    id: "16",
    title: "Still Life with Vessels",
    year: 2024,
    medium: "Oil on Canvas",
    dimensions: '28" × 36"',
    description: "A classical arrangement of vintage ceramics and dried botanicals. Quiet beauty found in everyday objects.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/v1763031041/IMG_0102_qw7i8n.webp",
    category: "Still Life",
    price: "$2,200",
    sold: "false",
  },
  {
    id: "17",
    title: "Chromatic Energy",
    year: 2024,
    medium: "Acrylic on Canvas",
    dimensions: '36" × 48"',
    description: "Explosive color and dynamic movement. This piece embodies pure creative energy and spontaneous expression.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/a_-90/v1763031038/IMG_0111_bukgaq.webp",
    category: "Abstract",
    price: "$3,000",
    sold: "false",
  },
  {
    id: "18",
    title: "Zen Garden",
    year: 2023,
    medium: "Oil on Canvas",
    dimensions: '32" × 24"',
    description: "Minimalist composition inspired by Japanese rock gardens. A meditation on simplicity, balance, and tranquility.",
    imageUrl: "https://res.cloudinary.com/dq6x48o03/image/upload/a_-90/v1763031140/IMG_0075_qpbuhe.webp",
    category: "Landscape",
    price: "$2,300",
    sold: "false",
  },
];
